FROM stacks-blockchain:buster

WORKDIR /src

RUN apt-get update
RUN apt-get install -y wget jq screen net-tools ncat sqlite3 xxd openssl curl lsof

ENV PATH="/src/target/debug:/src/net-test/bin:${PATH}"
